name: niskala_service_gen
description: >
    A Dart code generator that creates strongly-typed API services using Dio
    from OpenAPI/OData metadata.
version: 1.0.0
homepage: https://github.com/plwep/niskala-service-gen

executables:
    niskala_service_gen: niskala_service_gen

environment:
    sdk: ">=3.10.4 <4.0.0"

dependencies:
    analyzer: ^10.0.0
    args: ^2.4.2
    code_builder: ^4.5.0
    dart_style: ^3.1.3
    dio: ^5.3.3
    logging: ^1.2.0
    path: ^1.8.0
    watcher: ^1.1.0
    yaml: ^3.1.3
    yaml_edit: ^2.1.0

dev_dependencies:
    coverage: ^1.7.2
    lints: ^6.0.0
    test: ^1.25.6
    very_good_analysis: ^5.1.0
